name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this is the correct branch name (e.g., main or master)

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Change to ubuntu-latest for better compatibility

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Ensure this matches your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the Eleventy site
      run: npx eleventy

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Ensure this matches your output folder

    # Cleanup step is optional and can be removed if unnecessary
    - name: Cleanup gh-pages cache
      run: git worktree prune && rm -rf .git/worktrees/gh-pages/
